[package]
name = "process-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13"
sysinfo = "0.20"
clap = "2.3"
hyper = {version = "0.14", features = ["full"]}
tokio = {version = "1", features = ["full"]}